# Generated by Django 4.1.7 on 2023-03-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='age',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.CharField(max_length=200, null='True'),
            preserve_default='True',
        ),
    ]
