# Generated by Django 4.2 on 2023-04-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_rename_age_lead_phone_number_lead_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
